version: 0.2

phases:  # Specify Corretto 17 as the Java runtime version
  pre_build:
    commands:
      - echo "Installing custom Java runtime"
      - curl -L -o corretto.tar.gz https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz  # Update the version and platform
      - tar xvf corretto.tar.gz
      - export JAVA_HOME=$PWD/amazon-corretto-17.0.7.7.1-linux-x64/jdk  # Update the path to your Corretto 17 JDK
      - export PATH=$JAVA_HOME/bin:$PATH

  build:
    commands:
      - java -version  # Verify that Corretto 17 is being used
      - echo Build started on `date`
      - mvn install    # Run the build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo The build version is $CODEBUILD_BUILD_ID
      - echo The project name is $CODEBUILD_PROJECT_NAME
      - echo The build number is $CODEBUILD_BUILD_NUMBER
      - echo The source version is $CODEBUILD_SOURCE_VERSION
      - echo The branch name is $CODEBUILD_SOURCE_VERSION
      - echo The repository name is $CODEBUILD_SOURCE_REPO_URL
      - echo The repository type is $CODEBUILD_SOURCE_REPO_URL
      - echo The source provider is $CODEBUILD_SOURCE_PROVIDER
artifact:
  files:
    - target/*.jar
  discard-paths: yes