version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the project...
      - mvn install
      - echo Build completed on `date`
artifacts:
    files:
        - target/*.jar
