version: 0.2

phases:
  install:
      runtime-versions:
        java: corretto17
  pre_build:
    commands:
      - yum install java-17-amazon-corretto-devel -y
      - alternatives --set java /usr/lib/jvm/java-17-amazon-corretto/bin/java

  build:
    commands:
      - java -version  # Verify that Corretto 17 is being used
      - echo Build started on `date`
      - mvn clean install    # Run the build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo The build version is $CODEBUILD_BUILD_ID
      - echo The project name is $CODEBUILD_PROJECT_NAME
      - echo The build number is $CODEBUILD_BUILD_NUMBER
      - echo The source version is $CODEBUILD_SOURCE_VERSION
      - echo The branch name is $CODEBUILD_SOURCE_VERSION
      - echo The repository name is $CODEBUILD_SOURCE_REPO_URL
      - echo The repository type is $CODEBUILD_SOURCE_REPO_URL
      - echo The source provider is $CODEBUILD_SOURCE_PROVIDER
artifact:
  files:
    - target/*.jar