version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Entered the install phase...
      - echo Installing Maven...
      - yum install maven -y
      - echo Maven installed successfully
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the project...
      - mvn install
      - echo Build completed on `date`
  post_build:
        commands:
            - echo Entered the post_build phase...
            - echo Nothing to do in the post_build phase...
artifacts:
    files:
        - target/*.jar
